### ISSUE TITLE
Document common scenarios

### ISSUE THREAD

**Issue by jh3y** [nearform/react-animation#10]
It could be beneficial to document how certain common scenarios could be handled with this package.

For example, how would you animate changes in a list? Do you have to wrap every child that needs animation?

How much effort is involved to implement support like in `ReactCSSTransitionGroup` where everything nested is individually detected? ([ref](https://reactjs.org/docs/animation.html#animating-one-or-zero-items))

**Comment by juliangoacher** [comment]
A new `AnimateGroup` component has been added, specifically for animating the additional and removal of components from a group, and will be included in the v1.2 release. Documentation and examples of use are in the readme and example page. The new component is implemented using `ReactTransitionGroup` and provides a simplified animation interface, in line with the other components in this lib.
