### ISSUE TITLE
Remove use of setTimeout

### ISSUE THREAD

**Issue by jh3y** [nearform/react-animation#11]
In `AnimateOnChange` @ [line 39](https://github.com/nearform/react-animation/blob/master/src/AnimateOnChange/index.js#L39) `setTimeout` is used with the `durationOut` prop. 

However, this may not be the most reliable. Opting to hook into `animationend`/`transitionend` events should yield a more reliable solution. As it's not passing the animation to the children and it's applying it to the container binding to those events shouldn't be too tricky.

```js
const [animation, setAnimation] = useState('')
  const [displayContent, setDisplayContent] = useState(children)
  const container = useRef(null)
  useEffect(() => {
    setAnimation('out')
    const handler = () => {
      setAnimation('in')
      setDisplayContent(children)
    }
    container.current.addEventListener('transitionend', handler)
    container.current.addEventListener('animationend', handler)
    return () => {
      container.current.removeEventListener('transitionend', handler)
      container.current.removeEventListener('animationend', handler)
    }
  }, [children])
```

**Comment by juliangoacher** [comment]
Browser support for the transitionend and animationend events seems good:

https://caniuse.com/#search=transitionend
https://caniuse.com/#search=animationend
