### ISSUE TITLE
useLayoutEffect use

### ISSUE THREAD

**Issue by jh3y** [nearform/react-animation#12]
Tinkering with the hook usage inside `AnimateOnChange`, using `useEffect` yielded the same result for me as using `useLayoutEffect`. However, I may have missed the scenario where it's needed.

From the docs, `useEffect` is the preferred method unless `useLayoutEffect` is an absolute requirement. `Prefer the standard useEffect when possible to avoid blocking visual updates.`

I tried with
```js
const [animation, setAnimation] = useState('')
  const [displayContent, setDisplayContent] = useState(children)
  const container = useRef(null)
  useEffect(() => {
    setAnimation('out')
    const handler = () => {
      setAnimation('in')
      setDisplayContent(children)
    }
    container.current.addEventListener('transitionend', handler)
    container.current.addEventListener('animationend', handler)
    return () => {
      container.current.removeEventListener('transitionend', handler)
      container.current.removeEventListener('animationend', handler)
    }
  }, [children])
```
As stated though, I may have missed a scenario where this was doing something.

**Comment by juliangoacher** [comment]
Browser support for the transitionend and animationend events seems good:

https://caniuse.com/#search=transitionend
https://caniuse.com/#search=animationend
