### ISSUE TITLE
broken npm package v1.0.7

### ISSUE THREAD

**Issue by euphocat** [nearform/react-animation#15]
Hi ! when doing a `yarn add react-animation@1.0.7` we get an almost empty dependency without a `dist` folder. Is this release actually broken?

**Comment by markhicken** [comment]
Noticing the same thing here for all versions.

**Comment by donovanh** [comment]
Sorry about this, I've been away for a while, will check to see what might have happened

**Comment by donovanh** [comment]
Version `1.0.9` is now pushed that includes the right files. Sorry about the mixup @euphocat and @markhicken - thanks for letting me know.
